---
- hosts: desktops
  become: true
  tasks:

  - name: Update repository index for Linux Mint, autoclean and autoremove
    apt:
      update_cache: yes
      autoclean: yes
      autoremove: yes
    when: ansible_distribution == "Linux Mint"

  - name: install tools
    apt:
      name:
        - vim
        - ncdu
        - vifm
      state: latest
    when: ansible_distribution == "Linux Mint"

  - name: Install a .deb package from the internet
    apt:
        deb: https://ilsh.duckdns.org/DEB/Shavit_Scripts_3.2_all.deb
    when: ansible_distribution == "Linux Mint"

  - name: copy .bashrc_root
    copy:
      src: /home/ilan/Ansible/.bashrc_root
      dest: /root/.bashrc

  - name: copy .bash_aliases
    copy:
      src: /home/ilan/Ansible/.bash_aliases
      dest: /root

  - name: copy .vimrc
    copy:
      src: /home/ilan/Ansible/.vimrc
      dest: /root

