---
- hosts: lampservers
  become: true
  tasks:

  - name: Update repository index for Debian, autoclean and autoremove
    apt:
      update_cache: yes
      upgrade: 'yes'
      autoclean: yes
      autoremove: yes
    when: ansible_distribution == "Debian"

  - name: install all lamp components
    apt:
      name:
        - apache2
        - php
        - mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

  - name: install tools
    apt:
      name:
        - vim-nox
        - ncdu
        - vifm
        - tmux
        - htop
      state: latest
    when: ansible_distribution == "Debian"

  - name: Install a .deb package from the internet
    apt:
        deb: https://ilsh.duckdns.org/ANSIBLE/Shavit_Scripts_3.2_all.deb
    when: ansible_distribution == "Debian"

  - name: copy .bashrc_root to /root
    copy:
      src: /home/ilan/Ansible/.bashrc_root
      dest: /root/.bashrc
      owner: root
      group: root
      mode: 0644

  - name: copy .bashrc to PI user
    copy:
      src: /home/ilan/Ansible/.bashrc
      dest: /home/pi/
      owner: pi
      group: pi
      mode: 0644

  - name: copy .bash_aliases to /root
    copy:
      src: /home/ilan/Ansible/.bash_aliases
      dest: /root/
      owner: root
      group: root
      mode: 0644

  - name: copy .bash_aliases to PI user
    copy:
      src: /home/ilan/Ansible/.bash_aliases
      dest: /home/pi/
      owner: pi
      group: pi
      mode: 0644

  - name: copy .vimrc to /root
    copy:
      src: /home/ilan/Ansible/.vimrc
      dest: /root
      owner: root
      group: root
      mode: 0644

  - name: copy .vimrc to PI user
    copy:
      src: /home/ilan/Ansible/.vimrc
      dest: /home/pi/
      owner: pi
      group: pi
      mode: 0644

  - name: update .vim dir for root
    unarchive:
      src: https://ilsh.duckdns.org/ANSIBLE/vim_config.zip
      dest: /root/
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: update .vim dir to PI user
    unarchive:
      src: https://ilsh.duckdns.org/ANSIBLE/vim_config.zip
      dest: /home/pi/
      remote_src: yes
      mode: 0755
      owner: pi
      group: pi

  - name: copy .tmux.conf to /root
    copy:
      src: /home/ilan/Ansible/.tmux.conf
      dest: /root
      owner: root
      group: root
      mode: 0644

  - name: copy .tmux.conf to PI user
    copy:
      src: /home/ilan/Ansible/.tmux.conf
      dest: /home/pi
      owner: pi
      group: pi
      mode: 0644

